#config_version=5

mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started: score_slide
  player_added:
    new_player_slide:
      priority: 1000
      
slides:
  score_slide:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 20
        y: 18
      - type: text
        text: PLAYER (number)
        y: 0
        x: 10
        font_size: 10
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 0
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 10
  new_player_slide:
    expire: 1s
    widgets:
      - type: text
        text: PLAYER (num) ADDED
        font_size: 10

