#config_version=5

mode:
  start_events: ball_starting
  priority: 100

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_TARDIS_vuk_ball_eject_success
    auto_launch: yes
    balls_to_save: 1
    debug: yes

achievements:
  Doctor_1:
    enable_events: TARDIS_Lit
    start_events: mode_Doctor_1_started
    stop_events: mode_Doctor_1_will_stop
    complete_events: Doctor_1_complete
    show_tokens:
      lights: l_Doctor_1
    restart_on_next_ball_when_started: false
  Doctor_2:
    enable_events: Doctor_1_complete && TARDIS_Lit
    start_events: mode_Doctor_2_started
    stop_events: mode_Doctor_2_will_stop
    complete_events: Doctor_2_complete
    show_tokens:
      lights: l_Doctor_2
    restart_on_next_ball_when_started: false
  Doctor_3:
    enable_events: Doctor_1_complete && Doctor_2_complete && TARDIS_Lit
    start_events: mode_Doctor_3_started
    stop_events: mode_Doctor_3_will_stop
    complete_events: Doctor_3_complete
    show_tokens:
      lights: l_Doctor_3
    restart_on_next_ball_when_started: false
  Doctor_4:
    enable_events: Doctor_1_complete && Doctor_2_complete && Doctor_3_complete && TARDIS_Lit
    start_events: mode_Doctor_4_started
    stop_events: mode_Doctor_4_will_stop
    complete_events: Doctor_4_complete
    show_tokens:
      lights: l_Doctor_4
    restart_on_next_ball_when_started: false
  Doctor_5:
    enable_events: Doctor_1_complete && Doctor_2_complete && Doctor_3_complete && Doctor_4_complete && TARDIS_Lit
    start_events: mode_Doctor_5_started
    stop_events: mode_Doctor_5_will_stop
    complete_events: Doctor_5_complete
    show_tokens:
      lights: l_Doctor_5
    restart_on_next_ball_when_started: false
  Doctor_6:
    enable_events: Doctor_1_complete && Doctor_2_complete && Doctor_3_complete && Doctor_4_complete && Doctor_5_complete && TARDIS_Lit
    start_events: mode_Doctor_6_started
    stop_events: mode_Doctor_6_will_stop
    complete_events: Doctor_6_complete
    show_tokens:
      lights: l_Doctor_6
    restart_on_next_ball_when_started: false
  Doctor_7:
    enable_events: Doctor_1_complete && Doctor_2_complete && Doctor_3_complete && Doctor_4_complete && Doctor_5_complete && Doctor_6_complete && TARDIS_Lit
    start_events: mode_Doctor_7_started
    stop_events: mode_Doctor_7_will_stop
    complete_events: Doctor_7_complete
    show_tokens:
      lights: l_Doctor_7
    restart_on_next_ball_when_started: false
  Doctor_8:
    enable_events: Doctor_1_complete && Doctor_2_complete && Doctor_3_complete && Doctor_4_complete && Doctor_5_complete && Doctor_6_complete && Doctor_7_complete && TARDIS_Lit
    start_events: mode_Doctor_8_started
    stop_events: mode_Doctor_8_will_stop
    complete_events: Doctor_8_complete
    restart_on_next_ball_when_started: false
  Doctor_War:
    enable_events: TARDIS1_group_complete && TARDIS_Lit
    start_events: mode_normandyattack_started
    complete_events: mode_normandyattack_will_stop
    restart_on_next_ball_when_started: false
#  Doctor_9:
#    enable_events:
#      - mode_normandyattack_started
#      - reenable_suicidemission 
#    start_events: missionselect_suicide_selected
#    stop_events: suicidemission_failed
#    disable_events: reset_from_suicide
#    complete_events: suicidemission_complete
#    restart_on_next_ball_when_started: true
#  Doctor_10:
#    enable_events: achievement_normandyattack_state_completed{device.achievements.omegarelay.state=="disabled"}
#    reset_events: suicidemission_failed
#    select_events: missionselect_suicide_selected
#    complete_events: omegarelay_complete
#  Doctor_11:
#    enable_events: achievement_normandyattack_state_completed{device.achievements.infiltration.state=="disabled"}
#    reset_events: suicidemission_failed
#    select_events: omegarelay_complete
#    complete_events: infiltration_complete
#  Doctor_12:
#    enable_events: achievement_normandyattack_state_completed{device.achievements.longwalk.state=="disabled"}
#    reset_events: suicidemission_failed
#    select_events: infiltration_complete
#    complete_events: longwalk_complete
#  Doctor_13:
#    enable_events: achievement_normandyattack_state_completed{device.achievements.tubes.state=="disabled"}
#    reset_events: suicidemission_failed
#    select_events: longwalk_complete
#    complete_events: tubes_complete
#  Gallifrey_Stands:
#    enable_events: achievement_normandyattack_state_completed{device.achievements.humanreaper.state=="disabled"}
#    reset_events: suicidemission_failed
#    select_events: tubes_complete
#    complete_events: humanreaper_complete

achievement_groups:
  TARDIS1_group:
    achievements: Doctor_1, Doctor_2, Doctor_3, Doctor_4, Doctor_5, Doctor_6, Doctor_7, Doctor_8
    events_when_all_completed: Doctor_War_Ready
    rotate_right_events: sw_Right_Flipper
    rotate_left_events: sw_Left_Flipper
    debug: true

#  TARDIS2_group:
#    achievements: TARDIS1_group, Doctor_War, Doctor_9, Doctor_10, Doctor_11, Doctor_12, Doctor_13
#    events_when_all_completed: Gallifrey_Ready
#    debug: true

slide_player:
  single_player_ball_started: slide_1
  player_1_multiplayer_slide: slide_2
  player_2_ball_started: slide_3
  player_3_ball_started: slide_4
  player_4_ball_started: slide_5
      
slides:
  slide_1:
  - type: text
    text: (player1|score)
    number_grouping: true
    min_digits: 2
    y: middle+2
      #persist_slide: yes
    style: tall title
  - type: text
    text: BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

  slide_2:
  - type: text
    text: (player1|score)
      #font: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

  slide_3:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
#      font: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player2|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

  slide_4:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
#      font: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player3|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

  slide_5:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
#      font: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player4|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1