#config_version=5

mode:
  start_events: ball_starting
  stop_events: ball_ended
  priority: 120

counters:
  lb_Top_Ramp_count:
    count_events: Top_Ramp_Shot_complete
    events_when_hit: Top_Ramp_done
    starting_count: 1
    direction: up
    persist_state: false

shots:
  Top_Ramp_Enter:
    switch: s_Enter_Top_Ramp_Opto
  Top_Ramp_Score:
    switch: s_Score_Top_Ramp

shot_groups:
  Top_Ramp_Shot:
    shots: Top_Ramp_Enter, Top_Ramp_Score
    reset_events: 
      Top_Ramp_Shot_complete: 1s

variable_player:
  mode_Doctor_6_started:
    pf_multiplier:
      float: 1
      action: set
  Top_Ramp_done{count==2}:
    pf_multiplier:
      float: 1.5
      action: set
  Top_Ramp_done{count==3}:
    pf_multiplier:
      float: 2
      action: set
  Top_Ramp_done{count==4}:
    pf_multiplier:
      float: 2.5
      action: set
  Top_Ramp_done{count==5}:
    pf_multiplier:
      float: 3
      action: set
  Top_Ramp_done{count==6}:
    pf_multiplier:
      float: 3.5
      action: set
  Top_Ramp_done{count==7}:
    pf_multiplier:
      float: 4
      action: set
  Top_Ramp_Shot_complete:
    score: 5000000 * current_player.pf_multiplier|block

show_player:
  mode_Doctor_6_started:
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_1_5X, f_Doctor_6_O
  Top_Ramp_done{count==2}:
    Playfield_1_5X_On:
      show_tokens:
        lights: l_1_5X
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_2X, l_Doctor_6, f_Doctor_6_O
  Top_Ramp_done{count==3}:
    Playfield_2X_On:
      show_tokens:
        lights: l_1_5X, l_2X
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_2_5X, l_Doctor_6, f_Doctor_6_O
  Top_Ramp_done{count==4}:
    Playfield_2_5X_On:
      show_tokens:
        lights: l_1_5X, l_2X, l_2_5X
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_3X, l_Doctor_6, f_Doctor_6_O
  Top_Ramp_done{count==5}:
    Playfield_3X_On:
      show_tokens:
        lights: l_1_5X, l_2X, l_2_5X, l_3X
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_3_5X, l_Doctor_6, f_Doctor_6_O
  Top_Ramp_done{count==6}:
    Playfield_3_5X_On:
      show_tokens:
        lights: l_1_5X, l_2X, l_2_5X, l_3X, l_3_5X
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_4X, l_Doctor_6, f_Doctor_6_O
  Top_Ramp_done{count>=7}:
    Playfield_4X_On:
      show_tokens:
        lights: l_1_5X, l_2X, l_2_5X, l_3X, l_3_5X, l_4X
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_Doctor_6