#config_version=5

mode:
  start_events: carousel_Doctor7_selected
  stop_events: ball_ended
  priority: 130

show_player:
  mode_Doctor_7_started:
    mccoy:
      loops: 0
      speed: 1

#raise up mini playfield to station 2 and hit targets