#config_version=5

ball_devices:
  bd_trough:
    ball_switches: s_trough_1, s_trough_2, s_trough_3
    eject_coil: c_Trough
    confirm_eject_type: target
    eject_targets: bd_plunger
    tags: trough, home, drain

  bd_drain:
    ball_switches: s_Outhole
    eject_coil: c_Outhole
    eject_targets: bd_trough
    tags: drain, outhole

  bd_plunger:
    ball_switches: s_Shooter_Lane
    eject_coil: c_Shooter
    player_controlled_eject_event: s_Launch_Ball_active
    eject_timeouts: 3s

  bd_TARDIS_vuk:
    ball_switches: s_Opto_Popper
    eject_coil: c_Opto_Popper

  bd_Left_Lock:
    ball_switches: s_Mini_Left_Opto_Eject
    eject_coil: c_Mini_Left_Opto_Eject

  bd_Right_Lock:
    ball_switches: s_Mini_Right_Opto_Eject
    eject_coil: c_Mini_Right_Opto_Eject