#config_version=5

flippers: 
  left_flipper: 
    main_coil: c_flipper_left_main 
    hold_coil: c_flipper_left_hold 
    activation_switch: s_Left_Flipper_Opto
    label: Left Main Flipper
        
  right_flipper: 
    main_coil: c_flipper_right_main 
    hold_coil: c_flipper_right_hold 
    activation_switch: s_Right_Flipper_Opto
    label: Right Main Flipper

  upper_left_flipper: 
    main_coil: c_flipper_upper_left_main 
    hold_coil: c_flipper_upper_left_hold 
    activation_switch: s_Upper_Left_Flipper_Opto
    enable_events: ball_started, enable_upper_flippers
    disable_events: ball_will_end, service_mode_entered, disable_upper_flippers
    label: Left Upper Flipper   

  upper_right_flipper: 
    main_coil: c_flipper_upper_right_main 
    hold_coil: c_flipper_upper_right_hold 
    activation_switch: s_Upper_Right_Flipper_Opto
    enable_events: ball_started, enable_upper_flippers
    disable_events: ball_will_end, service_mode_entered, disable_upper_flippers
    label: Right Upper Flipper