#config_version=5
keyboard:
  s:
    switch: s_Start_Button
  1:
    switch: s_trough_1
    toggle: true
  x:
    switch: s_Left_Sling
  z:
    switch: s_Left_Flipper_Opto
  /:
    switch: s_Right_Flipper_Opto
  .:
    switch: s_Right_Sling
  l:
    switch: s_Launch_Ball
    