#config_version=5
keyboard:
  s:
    switch: s_credit
  1:
    switch: s_trough_1
    toggle: true
  x:
    switch: s_left_slingshot
  z:
    switch: s_left_flipper
  /:
    switch: s_right_flipper
  .:
    switch: s_right_slingshot

    