#config_version=5
keyboard:
  s:
    switch: s_Start_Button
  1:
    switch: s_trough_1
    toggle: true
  x:
    switch: s_Left_Sling
  z:
    switch: s_Left_Flipper_Opto
  /:
    switch: s_Right_Flipper_Opto
  .:
    switch: s_Right_Sling
  l:
    switch: s_Launch_Ball


  2:
    switch: s_REPAIR_R1
  3:
    switch: s_REPAIR_E
  4:
    switch: s_REPAIR_P
  5:
    switch: s_REPAIR_A
  6:
    switch: s_REPAIR_I
  7:
    switch: s_REPAIR_R2

  o:
    switch: s_Enter_Top_Ramp_Opto
  p:
    switch: s_Score_Top_Ramp
  i:
    switch: s_Hangon_Score


  b:
    switch: s_Left_Jet
  n:
    switch: s_Right_Jet
  m:
    switch: s_Bottom_Jet

  t:
    switch: s_Opto_Popper