#config_version=5

lights:

  l_example:
    number: l11
    subtype: matrix
    label:
    tags:

  f_Second_Chance:
    number: c06
    label:
    tags:

  f_Doctor_3:
    number: c08
    label:
    tags:

  f_Backbox_Head:
    number: c14
    label:
    tags:

  f_Doctor_7_Mini:
    number: c17
    label:
    tags:

  f_5x3_Left:
    number: c18
    label:
    tags:

  f_5x3_Right:
    number: c19
    label:
    tags:

  f_Doctor_5_Jets:
    number: c20
    label:
    tags:

  f_Doctor_4_REPAIR:
    number: c21
    label:
    tags:

  f_Doctor_2_H:
    number: c22
    label:
    tags:

  f_Doctor_6_O:
    number: c23
    label:
    tags:

  f_Doctor_1_ESCAPE:
    number: c24
    label:
    tags:

  f_Mini_CCW_CW:
    number: c27
    label:
    tags:

  f_Mini_On_Off:
    number: c28
    label:
    tags:


  gi_Insert_1:
    number: g01
    label:
    tags:

  gi_Insert_2:
    number: g02
    label:
    tags:

  gi_Playfield_A:
    number: g03
    label:
    tags:

  gi_Playfield_B:
    number: g04
    label:
    tags:

  gi_Playfield_C:
    number: g05
    label:
    tags: