#config_version=5


switches:
  s_left_flipper:
    number: 0 
    tags: left_flipper

  s_trough_3:
    number: 38
    tags: 

  s_trough_2:
    number: 39
    tags:

  s_trough_1:
    number: 40
    tags: 