#config_version=5

mode:
  start_events: carousel_Doctor8_selected
  stop_events: ball_ended
  priority: 130

show_player:
  mode_Doctor_8_started:
    mcgann:
      loops: 0
      speed: 1
#raise up mini playfield to station 2 and hit targets